# General settings
title: Allison Spencer Hartnett
title_html: "Allison Spencer Hartnett"
description:
  en: Research Fellow at Harvard Kennedy School
baseurl: ""
url: "https://ashartnett.github.io"

langs: ["en"]
defaults:
  - scope:
      path: ""
    values:
      lang: "en"

# Author
author: Allison Spencer Hartnett

email: allison_hartnett@hks.harvard.edu
twitter_username: as_hartnett
github_username: ashartnett
linkedin_username: allisonhartnett
author_website: https://ashartnett.github.io

# Favicon
favicon:
  safari: 5bbad5
  theme: ffffff

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["tables", "fenced_code_blocks", "autolink", "footnotes", "with_toc_data"]
theme: academic
plugins:
  - jekyll-feed
exclude:
  - jekyll_build.sh
  - Gemfile
  - Gemfile.lock
