# General settings
title: Allison Spencer Hartnett
title_html: "Allison Spencer Hartnett"
description:
  en: Assistant Professor, USC
baseurl: ""
url: "https://ashartnett.github.io"

langs: ["en"]
defaults:
  - scope:
      path: ""
    values:
      lang: "en"

# Author
author: Allison Spencer Hartnett

email: ahartnet@usc.edu
twitter_username: as_hartnett
github_username: ashartnett
linkedin_username: allisonhartnett
author_website: www.allisonhartnett.io

# Favicon
favicon:
  safari: 5bbad5
  theme: ffffff

# Build settings
markdown: kramdown
remote_theme: gaalcaras/academic
#plugins:
plugins_dir:
  - jekyll-feed
  - jekyll-remote-theme
exclude:
  - jekyll_build.sh
  - Gemfile
  - Gemfile.lock
